from django.urls import path
from .import views

urlpatterns = [
    path('', views.home,name="home"),
    path('home', views.home,name="home"),
    path('all', views.all),
    path('userLogin', views.userLogin, name='userLogin'),
    path('userLogout', views.userLogout, name='userLogout'),
    path('registerAccount', views.registerAccount, name='registerAccount'),
    path('forgetPassword', views.forgetPassword, name='forgetPassword'),
    path('createOnlineBooking', views.createOnlineBooking, name='createOnlineBooking'),
    path('all_admin', views.all_admin),
    path('adminHome', views.adminHome, name='adminHome'),
    path('onlineBookingInfor', views.onlineBookingInfor, name='onlineBookingInfor'),
    path('editOnlineBooking/<id>', views.editOnlineBooking, name='editOnlineBooking'),
    path('AddCustomer', views.AddCustomer, name='AddCustomer'),
    path('AllCustomer', views.AllCustomer, name='AllCustomer'),
    path('EditCustomer/<id>', views.EditCustomer, name='EditCustomer'),
    path('deleteOnlineBooking/<id>', views.deleteOnlineBooking, name='deleteOnlineBooking'),
    # path('Search', views.Search, name='Search'),
    path('AddCustpage_Delete/<id>', views.AddCustpage_Delete, name='AddCustpage_Delete'),
    path('AllCustpage_Delete/<id>', views.AllCustpage_Delete, name='AllCustpage_Delete'),
    path('addRoom', views.addRoom, name='addRoom'),
    path('Add_Room_Search', views.Add_Room_Search, name='Add_Room_Search'),
    path('AddRooms_Delete/<id>', views.AddRooms_Delete, name='AddRooms_Delete'),
    path('editRoom/<id>', views.editRoom, name='editRoom'),
    path('allRoom', views.allRoom, name='allRoom'),
    path('AllRooms_Delete/<id>', views.AllRooms_Delete, name='AllRooms_Delete'),
]