# Generated by Django 4.1.3 on 2023-05-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='online_booking',
            old_name='Customer_Id',
            new_name='Customer',
        ),
    ]
